<?php

namespace app\logic;

use app\library\RichText;
use app\model\Agreement;


class AgreementLogic extends BaseLogic
{
    protected static string $model    = Agreement::class;
    protected static bool   $useCache = TRUE;
    
    public static function modify(int|array|string $idOrCondition, array $data): bool
    {
        if (!empty($data['content'])) {
            $data['content_array'] = RichText::htmlToArray($data['content']);
        }
        return parent::modify($idOrCondition, $data); // TODO: Change the autogenerated stub
    }
    
    public static function create($data): bool|int
    {
        if (!empty($data['content'])) {
            $data['content_array'] = RichText::htmlToArray($data['content']);
        }
        return parent::create($data); // TODO: Change the autogenerated stub
    }
    
}