<?php

namespace app\logic;

use app\model\Banner;

class BannerLogic extends BaseLogic
{
    protected static string $model = Banner::class;
    
    protected static bool $useCache = TRUE;
    
    public static function formatSaveData($data, bool $isEdit = FALSE): array
    {
        $data['start_at'] = now(strtotime($data['start_at'] ?? now()));
        $data['end_at']   = now(strtotime($data['end_at'] ?? now(time() + 86400 * 90)));
        return parent::formatSaveData($data, $isEdit); // TODO: Change the autogenerated stub
    }
    
    /**
     * 客户端获取数据
     *
     * @param array  $conditions
     * @param int    $pageSize
     * @param int    $page
     * @param string $sortBy
     * @param string $sortOrder
     *
     * @return array
     */
    public static function clientGetList(array $conditions = [], int $pageSize = 20, int $page = 1, string $sortBy = 'id', string $sortOrder = 'asc'): array
    {
        $conditions = array_merge($conditions, [
            ['status', 1],
            ['start_at', 'ngt', now()],
            ['end_at', 'nlt', now()],
        ]);
        // todo 筛选器啊
        $data = parent::clientGetList($conditions, $pageSize, $page, $sortBy, $sortOrder);
        $list = $data['list'];
        
        foreach ($list as $key => $value) {
            $list[$key]['img'] = $value['image'];
        }
        
        $data['list'] = $list;
        
        return $data;
        
    }
    
    public static function clientFormat($data): array
    {
        $data = parent::clientFormat($data);
    }
}